export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT';

export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';
export const FETCH_SINGLE_PRODUCT_FAILED = 'FETCH_SINGLE_PRODUCT_FAILED';

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_SINGLE_PRODUCT_REQUEST = 'FETCH_SINGLE_PRODUCT_REQUEST';
