export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const CREATE_PRODUCT_FAILED = 'CREATE_PRODUCT_FAILED';
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';